# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Latest Code
      run: git pull origin main
    - name: Run TestNG
      run: mvn test -DtestngXmlFile=testSuits/testng.xml
    - name: Commit Reports
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git status
          git add .
          git stash push -m "Stashing changes before commit via GitHub Actions"
         
          git push origin master
          git add Reports/*.html  # This will add all HTML files in the surefire-reports directory
          git status
          git commit -m "Update test reports via GitHub Actions"
          git push origin master
    
    - name: Archive code coverage results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Test-coverage-report
        path: target/surefire-reports/*.html
    

    - name: Run TestNG Tests
      run: mvn clean test  # Run TestNG tests using Maven
      
    - name: Publish Test Reports as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: Reports/*.html  # Path where TestNG reports are generated
